modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/Kotori316/FluidTank2/issues"
license = "All rights reserved"

[[mods]]
modId = "fluidtank"
version = "${version}"
displayName = "Fluid Tank"
displayURL = "https://github.com/Kotori316/FluidTank2"
modUrl = "https://github.com/Kotori316/FluidTank2"
updateJSONURL = "https://version.kotori316.com/get-version/1.20.1/forge/fluidtank"
credits = "Kotori316"
authors = "Kotori316"
description = '''
FluidTank
'''
logoFile = "assets/fluidtank/textures/icon.png"

[[dependencies.fluidtank]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fluidtank]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
