org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
minecraft_version=26.1.2
# Common setting
archives_base_name=largefluidtank
maven_base_name=fluidtank
mod_version=26.12.0
maven_group=com.kotori316
changelog_file=changelog/26.1.md
github_branch=26.1
scala3_version=3.8.4
cats_version=2.13.0
debug_util_version=26.1.0
automatic_potato_version=3.0.1
############################## Fabric ##############################
# https://maven.fabricmc.net/net/fabricmc/fabric-loader/
fabric_loader_version=0.19.3
fabric_api_version=0.152.1+26.1.2
# https://maven.kotori316.com/com/kotori316/scalable-cats-force-fabric
slp_fabric_version=5.0.0
# https://www.curseforge.com/minecraft/mc-mods/jade/files
jade_fabric_id=7886518
# https://maven.blamejared.com/mezz/jei/jei-26.1.2-fabric/
jei_fabric_repo_version=26.1.2
jei_fabric_version=29.6.2.31
# https://maven.fabricmc.net/teamreborn/energy/
fabric_energy_version=5.0.0
############################## Forge ##############################
forge_version=1.21.8-58.0.0
# https://maven.kotori316.com/com/kotori316/scalablecatsforce
slpVersion=5.0.0-mc26.1.2-3.8.4
# https://www.curseforge.com/minecraft/mc-mods/jade/files
jade_forge_id=4978952
# https://www.curseforge.com/minecraft/mc-mods/the-one-probe/files
top_forge_id=4629624
# https://maven.blamejared.com/mezz/jei/jei-1.21.1-forge/
jei_forge_repo_version=1.21.1
jei_forge_version=19.27.0.340
############################## Neo Forge ##############################
neoforge_version=26.1.2.76
slp_neoforge_version=5.0.0-mc26.1.2-3.8.4
# https://www.curseforge.com/minecraft/mc-mods/jade/files
jade_neoforge_id=7938398
# https://www.curseforge.com/minecraft/mc-mods/the-one-probe/files
top_neoforge_id=5502323
# https://modmaven.dev/appeng/appliedenergistics2-neoforge/
ae2_neoforge_version=19.2.0-beta
# https://maven.blamejared.com/mezz/jei/jei-26.1.2-neoforge/
jei_neoforge_repo_version=26.1.2
jei_neoforge_version=29.6.2.31
############################## Test Dependencies ##############################
# https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
jupiterVersion=6.1.0
# https://mvnrepository.com/artifact/org.mockito/mockito-core
mockitoCoreVersion=5.23.0
# https://mvnrepository.com/artifact/org.mockito/mockito-inline
mockitoInlineVersion=5.2.0
############################## 8.4 workaround ##############################
# https://docs.gradle.org/current/userguide/upgrading_version_8.html#xml_parsing_now_requires_recent_parsers
systemProp.javax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
systemProp.javax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl
systemProp.javax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
############################## NeoForge workaround ##############################
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
############################## Publish ##############################
forgeCurseProjectId=291006
fabricCurseProjectId=411564
modrinthProjectId=uMlJQMHT
