org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
minecraft_version=1.21.11
# Common setting
archives_base_name=largefluidtank
maven_base_name=fluidtank
mod_version=21.11.1
maven_group=com.kotori316
changelog_file=changelog/1.21.md
github_branch=1.21.11
# https://github.com/ParchmentMC/Parchment
# https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data
parchment_mapping_mc=1.21.11
parchment_mapping_version=2025.12.20
scala2_version=2.13.17
scala3_version=3.7.3
cats_version=2.13.0-kotori
debug_util_version=21.11.4
automatic_potato_version=2.6.1
############################## Fabric ##############################
# https://maven.fabricmc.net/net/fabricmc/fabric-loader/
fabric_loader_version=0.18.4
fabric_api_version=0.141.2+1.21.11
# https://maven.kotori316.com/com/kotori316/scalable-cats-force-fabric
slp_fabric_version=3.1.8
# https://www.curseforge.com/minecraft/mc-mods/jade/files
jade_fabric_id=7312559
# https://maven.blamejared.com/mezz/jei/jei-1.21.11-fabric/
jei_fabric_repo_version=1.21.11
jei_fabric_version=27.4.0.15
# https://maven.fabricmc.net/teamreborn/energy/
fabric_energy_version=4.2.0
############################## Forge ##############################
forge_version=1.21.8-58.0.0
# https://maven.kotori316.com/com/kotori316/scalablecatsforce
slpVersion=3.7.3-build-12
# https://www.curseforge.com/minecraft/mc-mods/jade/files
jade_forge_id=4978952
# https://www.curseforge.com/minecraft/mc-mods/the-one-probe/files
top_forge_id=4629624
# https://maven.blamejared.com/mezz/jei/jei-1.21.1-forge/
jei_forge_repo_version=1.21.1
jei_forge_version=19.27.0.340
############################## Neo Forge ##############################
neoforge_version=21.11.37-beta
slp_neoforge_version=3.7.3-build-12
# https://www.curseforge.com/minecraft/mc-mods/jade/files
jade_neoforge_id=7313008
# https://www.curseforge.com/minecraft/mc-mods/the-one-probe/files
top_neoforge_id=5502323
# https://modmaven.dev/appeng/appliedenergistics2-neoforge/
ae2_neoforge_version=19.2.0-beta
# https://maven.blamejared.com/mezz/jei/jei-1.21.11-neoforge/
jei_neoforge_repo_version=1.21.11
jei_neoforge_version=27.4.0.15
############################## Test Dependencies ##############################
# https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
jupiterVersion=6.0.2
# https://mvnrepository.com/artifact/org.mockito/mockito-core
mockitoCoreVersion=5.21.0
# https://mvnrepository.com/artifact/org.mockito/mockito-inline
mockitoInlineVersion=5.2.0
############################## 8.4 workaround ##############################
# https://docs.gradle.org/current/userguide/upgrading_version_8.html#xml_parsing_now_requires_recent_parsers
systemProp.javax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
systemProp.javax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl
systemProp.javax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
############################## NeoForge workaround ##############################
neogradle.subsystems.conventions.runs.create-default-run-per-type=false
