name: Java CI

on:
  push:
    branches: [ "1.20.1" ]
  pull_request:
    branches: [ "1.20.1" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - name: Tool chain check
        run: ./gradlew javaToolchains
      - name: Check build environments
        run: ./gradlew :buildEnvironment :forge:buildEnvironment :fabric:buildEnvironment
      - name: Check changelog
        run: ./gradlew checkChangelog
      - name: Check Release Version
        run: ./gradlew checkReleaseVersion
      - name: Generate Jar
        run: ./gradlew :fabric:remapJar :forge:remapJar
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FluidTank2-${{ github.run_number }}
          path: "*/build/libs/*.jar"
          if-no-files-found: error
          retention-days: 7

  common-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      FORGE_ONLY: true
      FABRIC_ONLY: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - name: Common JUnit
        run: ./gradlew :common:test

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        platform: [ forge, fabric ]
    env:
      FORGE_ONLY: ${{ matrix.platform == 'forge' }}
      FABRIC_ONLY: ${{ matrix.platform == 'fabric' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - name: ${{ matrix.platform }} JUnit
        run: ./gradlew :${{ matrix.platform }}:test
      - name: ${{ matrix.platform }} GameTest
        env:
          RUN_GAME_TEST: true
        run: ./gradlew :${{ matrix.platform }}:runGameTest

  forge-data-gen:
    runs-on: ubuntu-latest
    env:
      FORGE_ONLY: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - name: Compile
        run: ./gradlew :forge:genDataClasses
      - name: Prepare Run
        run: >-
          ./gradlew configureLaunch downloadAssets ||
          (sleep 5 && ./gradlew configureLaunch downloadAssets) ||
          (sleep 5 && ./gradlew configureLaunch downloadAssets)
      - name: Forge DataGen
        timeout-minutes: 5
        env:
          RUN_DATA_GEN: true
        run: ./gradlew :forge:runData
      - name: Check updated files
        run: git status
