name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache gradle
        uses: actions/cache@v3
        with:
          path: |
            .gradle
            */.gradle
          key: Gradle-Dot-${{ runner.os }}-${{ hashFiles('build.gradle', 'gradle.properties') }}
          restore-keys: Gradle-Dot-${{ runner.os }}-
      - run: chmod +x ./gradlew
      - name: Tool chain check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: javaToolchains
      - name: Generate Jar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :fabric:remapJar :forge:remapJar
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FluidTank2-${{ github.run_number }}
          path: "*/build/libs/*.jar"
          if-no-files-found: error
          retention-days: 7
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  forge-game-test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache gradle
        uses: actions/cache/restore@v3
        with:
          path: |
            .gradle
            */.gradle
          key: Gradle-Dot-${{ runner.os }}-${{ hashFiles('build.gradle', 'gradle.properties') }}
          fail-on-cache-miss: true
      - run: chmod +x ./gradlew
      - name: Forge GameTest
        uses: gradle/gradle-build-action@v2
        env:
          RUN_GAME_TEST: true
        with:
          arguments: :forge:runGameTest
  forge-data-gen:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache gradle
        uses: actions/cache/restore@v3
        with:
          path: |
            .gradle
            */.gradle
          key: Gradle-Dot-${{ runner.os }}-${{ hashFiles('build.gradle', 'gradle.properties') }}
          fail-on-cache-miss: true
      - run: chmod +x ./gradlew
      - name: Compile test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :forge:compileTestScala
      - name: Forge DataGen
        uses: gradle/gradle-build-action@v2
        timeout-minutes: 5
        env:
          RUN_DATA_GEN: true
        with:
          arguments: :forge:runData
  fabric-game-test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache gradle
        uses: actions/cache/restore@v3
        with:
          path: |
            .gradle
            */.gradle
          key: Gradle-Dot-${{ runner.os }}-${{ hashFiles('build.gradle', 'gradle.properties') }}
          fail-on-cache-miss: true
      - run: chmod +x ./gradlew
      - name: Fabric GameTest
        uses: gradle/gradle-build-action@v2
        env:
          RUN_GAME_TEST: true
        with:
          arguments: :fabric:runGameTest
