name: Java CI

on:
  push:
    branches: [ "26.2" ]
  pull_request:
    branches: [ "26.2" ]

permissions:
  contents: read

jobs:
  assemble:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - name: Setup Java JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          add-job-summary: 'on-failure'
      - run: ./gradlew javaToolchains assemble publishToMavenLocal --scan
      - run: ./gradlew checkChangelog
      - run: ./gradlew checkReleaseVersion
      - run: ./gradlew publishMods
      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: FluidTank2-${{ github.run_number }}
          path: "*/build/libs/*.jar"
          if-no-files-found: error
          retention-days: 7

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        platform:
          - common
          - fabric
          - neoforge
    env:
      DISABLE_FORGE: ${{ matrix.platform != 'forge' }}
      DISABLE_FABRIC: ${{ matrix.platform != 'fabric' }}
      DISABLE_NEOFORGE: ${{ matrix.platform != 'neoforge' }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - name: Setup Java JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          add-job-summary: 'on-failure'
      - name: ${{ matrix.platform }} JUnit
        run: ./gradlew :${{ matrix.platform }}:${{ matrix.platform == 'neoforge' && 'testJunit' || 'test' }}
        env:
          RUN_JUNIT: true
      - name: Prepare Runs
        if: ${{ matrix.platform == 'forge' }}
        timeout-minutes: 5
        run: ./gradlew downloadAssets || ./gradlew downloadAssets || true
        env:
          RUN_GAME_TEST: true
      - name: ${{ matrix.platform }} DataGen
        if: ${{ matrix.platform != 'common' }}
        run: ./gradlew :${{ matrix.platform }}:${{ matrix.platform == 'neoforge' && 'runClientData' || 'runData' }}
        timeout-minutes: 5
        env:
          TEST_UTILITY_LOG_ALL_DATA: true
          RUN_DATA_GEN: true
      - name: ${{ matrix.platform }} GameTest
        if: ${{ matrix.platform != 'common' }}
        timeout-minutes: 5
        run: ./gradlew :${{ matrix.platform }}:runGameTestServer
        env:
          TEST_UTILITY_LOG_ALL_TEST: true
          RUN_GAME_TEST: true
      - name: Check report
        run: |
          ! test -d "${{ matrix.platform }}/game-test/crash-reports"
      - name: Check updated files
        run: git status
      - name: Check diff
        run: git diff --exit-code -- ./${{ matrix.platform }}/src/generated
      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: FluidTank2-${{ github.run_number }}-test-${{ matrix.platform }}
          path: |
            build/reports
            game-test/logs
            game-test/crash-reports
          if-no-files-found: ignore
          retention-days: 1

  common-data-gen:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DISABLE_FORGE: true
      DISABLE_FABRIC: true
      DISABLE_NEOFORGE: false
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - name: Setup Java JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          add-job-summary: 'on-failure'
      - run: ./gradlew :neoforge:commonDataGenClasses
        env:
          TEST_UTILITY_LOG_ALL_DATA: true
          RUN_DATA_GEN: true
      - name: DataGen
        run: ./gradlew :neoforge:runCommonData
        timeout-minutes: 5
        env:
          TEST_UTILITY_LOG_ALL_DATA: true
          RUN_DATA_GEN: true
      - name: Check updated files
        run: git status
      - name: Check diff
        run: git diff --exit-code -- ./common/src/generated

  fabric-client-test:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 15
    container:
      image: mcr.microsoft.com/devcontainers/java:25
    permissions:
      id-token: write
      contents: read
    env:
      DISABLE_FORGE: true
      DISABLE_FABRIC: false
      DISABLE_NEOFORGE: true
      SCREENSHOT_DIR: /tmp/vrt/screenshots
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: '0'
      - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - name: Setup Java JDK
        if: false
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'temurin'
          java-version: '25'
      - run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-read-only: true
          add-job-summary: 'on-failure'
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y xvfb x11-xserver-utils pulseaudio libflite1 libopenal1
      - name: Start audio server
        if: false
        run: |
          pulseaudio --start --exit-idle-time=-1
          pactl load-module module-null-sink sink_name=DummyOutput
          pactl set-default-sink DummyOutput
      - run: |
          echo "path=$(find /usr/lib -name 'libopenal.so.1' | head -1)" >> $GITHUB_OUTPUT
        id: openal
      - name: Run client test
        timeout-minutes: 10
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" \
            ./gradlew runGameTestClient --no-daemon
        env:
          OPENAL_LIB: ${{ steps.openal.outputs.path }}
          ALSOFT_DRIVERS: 'null'
          JAVA_TOOL_OPTIONS: '-Dorg.lwjgl.openal.libname=${{ steps.openal.outputs.path }}'
      - run: ls -R "${SCREENSHOT_DIR}"
      - run: mkdir -p vrt/screenshots
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'
      - name: Check screenshots
        run: |
          set -x
          mv ${SCREENSHOT_DIR}/* vrt/screenshots
          ls -alR vrt/screenshots
      - run: npm ci
        working-directory: vrt
      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{secrets.GCP_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}
      - name: Get credentials
        id: get-secrets
        uses: google-github-actions/get-secretmanager-secrets@bc9c54b29fdffb8a47776820a7d26e77b379d262 # v3.0.0
        with:
          secrets: |-
            cloudflare_s3_endpoint:kotori316-mods-resources/cloudflare_s3_endpoint
            cloudflare_access_key:kotori316-mods-resources/cloudflare_access_key
            cloudflare_secret_key:kotori316-mods-resources/cloudflare_secret_key
      - name: workaround for detached HEAD
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          set -eux
          git config --global --add safe.directory $(pwd)
          git branch -vv
          git fetch
          git switch "${REF_NAME}"
          git pull || true
        env:
          REF_NAME: ${{ github.head_ref }}
      - name: Get sha
        id: get-sha
        uses: 'Kotori316/vrt-key-action@e30535495397ae854459b1d1d37e6e1ad7c13caa' # v2.2.0
        with:
          save-key: ${{ github.event_name == 'push' }}
      - name: VRT Push
        run: npm run "${COMMAND}"
        working-directory: vrt
        env:
          COMMAND: ${{ github.event_name == 'push' && 'run:ci-push' || 'run:ci-pr' }}
          EXPECTED_KEY: ${{ steps.get-sha.outputs.key }}
          ACTUAL_KEY: ${{ steps.get-sha.outputs.actual-key }}
          AWS_ACCESS_KEY_ID: ${{ steps.get-secrets.outputs.cloudflare_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.get-secrets.outputs.cloudflare_secret_key }}
          AWS_ENDPOINT_URL: ${{ steps.get-secrets.outputs.cloudflare_s3_endpoint }}
          AWS_REGION: auto

  merge-checker:
    if: always()
    needs:
      - assemble
      - test
    uses: 'Kotori316/common-script/.github/workflows/merge-checker.yaml@cc63e8610e21a91ed102150d078b10d216e02b76' # v2.0.3
    with:
      needs: ${{ toJSON(needs) }}
