name: Java CI

on:
  push:
    branches: [ "1.21.2" ]
  pull_request:
    branches: [ "1.21.2" ]

permissions:
  contents: read

jobs:
  assemble:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: 'false'
          job_summary: 'true'
          theme: 'dark'
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          add-job-summary: 'on-failure'
      - run: ./gradlew javaToolchains assemble publishToMavenLocal --scan
      - run: ./gradlew checkChangelog
      - run: ./gradlew checkReleaseVersion
      - run: ./gradlew publishMods
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FluidTank2-${{ github.run_number }}
          path: "*/build/libs/*.jar"
          if-no-files-found: error
          retention-days: 7

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        platform:
          - common
          - fabric
          - neoforge
    env:
      DISABLE_FORGE: ${{ matrix.platform != 'forge' }}
      DISABLE_FABRIC: ${{ matrix.platform != 'fabric' }}
      DISABLE_NEOFORGE: ${{ matrix.platform != 'neoforge' }}
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          comment_on_pr: 'false'
          job_summary: 'true'
          theme: 'dark'
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          add-job-summary: 'on-failure'
      - name: ${{ matrix.platform }} JUnit
        run: ./gradlew :${{ matrix.platform }}:${{ matrix.platform == 'neoforge' && 'testJunit' || 'test' }}
        env:
          RUN_JUNIT: true
      - name: Prepare Runs
        if: ${{ matrix.platform == 'forge' }}
        timeout-minutes: 5
        run: ./gradlew downloadAssets || ./gradlew downloadAssets || true
        env:
          RUN_GAME_TEST: true
      - name: ${{ matrix.platform }} DataGen
        if: ${{ matrix.platform != 'common' }}
        run: ./gradlew :${{ matrix.platform }}:${{ matrix.platform == 'neoforge' && 'runClientData' || 'runData' }}
        timeout-minutes: 5
        env:
          TEST_UTILITY_LOG_ALL_DATA: true
          RUN_DATA_GEN: true
      - name: ${{ matrix.platform }} GameTest
        if: ${{ matrix.platform != 'common' }}
        timeout-minutes: 5
        run: ./gradlew :${{ matrix.platform }}:runGameTestServer
        env:
          TEST_UTILITY_LOG_ALL_TEST: true
          RUN_GAME_TEST: true
      - name: Check report
        run: |
          ! test -d "${{ matrix.platform }}/game-test/crash-reports"
      - name: Check updated files
        run: git status
      - name: Check diff
        run: git diff --exit-code -- ./${{ matrix.platform }}/src/generated
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: FluidTank2-${{ github.run_number }}-test-${{ matrix.platform }}
          path: |
            build/reports
            game-test/logs
            game-test/crash-reports
          if-no-files-found: ignore
          retention-days: 1

  common-data-gen:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      DISABLE_FORGE: true
      DISABLE_FABRIC: true
      DISABLE_NEOFORGE: false
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.event_name != 'push' }}
          add-job-summary: 'on-failure'
      - run: ./gradlew :neoforge:commonDataGenClasses
        env:
          TEST_UTILITY_LOG_ALL_DATA: true
          RUN_DATA_GEN: true
      - name: DataGen
        run: ./gradlew :neoforge:runCommonData
        timeout-minutes: 5
        env:
          TEST_UTILITY_LOG_ALL_DATA: true
          RUN_DATA_GEN: true
      - name: Check updated files
        run: git status
      - name: Check diff
        run: git diff --exit-code -- ./common/src/generated

  fabric-client-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read
    env:
      DISABLE_FORGE: true
      DISABLE_FABRIC: false
      DISABLE_NEOFORGE: true
      SCREENSHOT_DIR: /tmp/vrt/screenshots
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: '0'
      - uses: gradle/actions/wrapper-validation@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true
          add-job-summary: 'on-failure'
      - name: Run client test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./gradlew runGameTestClient
      - run: ls -R "${SCREENSHOT_DIR}"
      - run: mkdir -p vrt/screenshots
      - name: Check screenshots
        run: |
          set -x
          mv ${SCREENSHOT_DIR}/* vrt/screenshots
          ls -alR vrt/screenshots
      - run: npm ci
        working-directory: vrt
      - uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{secrets.GCP_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}
      - name: Get credentials
        id: get-secrets
        uses: google-github-actions/get-secretmanager-secrets@v2
        with:
          secrets: |-
            cloudflare_s3_endpoint:kotori316-mods-resources/cloudflare_s3_endpoint
            cloudflare_access_key:kotori316-mods-resources/cloudflare_access_key
            cloudflare_secret_key:kotori316-mods-resources/cloudflare_secret_key
      - name: workaround for detached HEAD
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          set -eux
          git branch -vv
          git fetch
          git switch "${REF_NAME}"
          git pull || true
        env:
          REF_NAME: ${{ github.head_ref }}
      - name: Get sha
        id: get-sha
        uses: 'Kotori316/vrt-key-action@v2'
        with:
          save-key: ${{ github.event_name == 'push' }}
      - name: VRT Push
        run: npm run "${COMMAND}"
        working-directory: vrt
        env:
          COMMAND: ${{ github.event_name == 'push' && 'run:ci-push' || 'run:ci-pr' }}
          EXPECTED_KEY: ${{ steps.get-sha.outputs.key }}
          ACTUAL_KEY: ${{ steps.get-sha.outputs.actual-key }}
          AWS_ACCESS_KEY_ID: ${{ steps.get-secrets.outputs.cloudflare_access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.get-secrets.outputs.cloudflare_secret_key }}
          AWS_ENDPOINT_URL: ${{ steps.get-secrets.outputs.cloudflare_s3_endpoint }}
          AWS_REGION: auto

  merge-checker:
    if: always()
    needs:
      - assemble
      - test
    uses: 'Kotori316/common-script/.github/workflows/merge-checker.yaml@main'
    with:
      needs: ${{ toJSON(needs) }}
