name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - name: Tool chain check
        uses: gradle/gradle-build-action@v2
        with:
          arguments: javaToolchains
      - name: Generate Jar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :fabric:remapJar :forge:remapJar
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: FluidTank2-${{ github.run_number }}
          path: "*/build/*libs/*.jar"

  forge-game-test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: chmod +x ./gradlew
      - name: GameTest
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :forge:runGameTest
