name: Release
on:
  workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: chmod +x ./gradlew
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
          add-job-summary: 'on-failure'
      - name: Check Release Version
        run: ./gradlew checkReleaseVersion --no-daemon
        env:
          RELEASE_DEBUG: false
      - name: Compile
        run: ./gradlew testClasses --no-daemon
      - name: JUnit
        run: ./gradlew test --no-daemon
        env:
          RUN_JUNIT: true
      - name: Prepare GameTest
        run: |
          (./gradlew configureLaunch downloadAssets prepareRuns writeMinecraftClasspathGameTestServer --no-daemon) || \
            (sleep 5 && ./gradlew configureLaunch downloadAssets prepareRuns writeMinecraftClasspathGameTestServer --no-daemon) || \
            (sleep 5 && ./gradlew configureLaunch downloadAssets prepareRuns writeMinecraftClasspathGameTestServer --no-daemon) || true
      - name: GameTest
        run: ./gradlew runGameTest
        env:
          RUN_GAME_TEST: true

  release:
    needs: [ check ]
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    # See https://github.com/Kotori316/common-script/blob/main/.github/workflows/release-prod-gradle.yaml
    uses: 'Kotori316/common-script/.github/workflows/release-prod-gradle.yaml@main'
    with:
      sign_check_command: 'assemble publishToMavenLocal --no-daemon'
      release_command: 'assemble publishToMavenLocal publishMods registerVersion publish --continue --no-daemon'
      enable_signature_check: true
      java_version: '21'
      use_attestation: true
      use_gradle_cache: true
    secrets: inherit
